// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/v1/box.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type FormListQuestionTypeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*FormItems `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FormListQuestionTypeResp) Reset() {
	*x = FormListQuestionTypeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormListQuestionTypeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormListQuestionTypeResp) ProtoMessage() {}

func (x *FormListQuestionTypeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormListQuestionTypeResp.ProtoReflect.Descriptor instead.
func (*FormListQuestionTypeResp) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{1}
}

func (x *FormListQuestionTypeResp) GetList() []*FormItems {
	if x != nil {
		return x.List
	}
	return nil
}

type FormGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *FormGetReq) Reset() {
	*x = FormGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormGetReq) ProtoMessage() {}

func (x *FormGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormGetReq.ProtoReflect.Descriptor instead.
func (*FormGetReq) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{2}
}

func (x *FormGetReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type FormGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *FormStruct `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *FormGetResp) Reset() {
	*x = FormGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormGetResp) ProtoMessage() {}

func (x *FormGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormGetResp.ProtoReflect.Descriptor instead.
func (*FormGetResp) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{3}
}

func (x *FormGetResp) GetForm() *FormStruct {
	if x != nil {
		return x.Form
	}
	return nil
}

type FormSaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form *FormStruct `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *FormSaveReq) Reset() {
	*x = FormSaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormSaveReq) ProtoMessage() {}

func (x *FormSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormSaveReq.ProtoReflect.Descriptor instead.
func (*FormSaveReq) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{4}
}

func (x *FormSaveReq) GetForm() *FormStruct {
	if x != nil {
		return x.Form
	}
	return nil
}

type FormListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FormListReq) Reset() {
	*x = FormListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormListReq) ProtoMessage() {}

func (x *FormListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormListReq.ProtoReflect.Descriptor instead.
func (*FormListReq) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{5}
}

type FormListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*FormListResp_FormList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FormListResp) Reset() {
	*x = FormListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormListResp) ProtoMessage() {}

func (x *FormListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormListResp.ProtoReflect.Descriptor instead.
func (*FormListResp) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{6}
}

func (x *FormListResp) GetList() []*FormListResp_FormList {
	if x != nil {
		return x.List
	}
	return nil
}

// 表单结构 -----------
type FormStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormTitle string       `protobuf:"bytes,1,opt,name=form_title,json=formTitle,proto3" json:"form_title,omitempty"`
	SubTitle  string       `protobuf:"bytes,2,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	FormUuid  string       `protobuf:"bytes,3,opt,name=form_uuid,json=formUuid,proto3" json:"form_uuid,omitempty"`
	Items     []*FormItems `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *FormStruct) Reset() {
	*x = FormStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormStruct) ProtoMessage() {}

func (x *FormStruct) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormStruct.ProtoReflect.Descriptor instead.
func (*FormStruct) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{7}
}

func (x *FormStruct) GetFormTitle() string {
	if x != nil {
		return x.FormTitle
	}
	return ""
}

func (x *FormStruct) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *FormStruct) GetFormUuid() string {
	if x != nil {
		return x.FormUuid
	}
	return ""
}

func (x *FormStruct) GetItems() []*FormItems {
	if x != nil {
		return x.Items
	}
	return nil
}

type FormItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content          *FormItemContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	QuestionTypeName string           `protobuf:"bytes,2,opt,name=question_type_name,json=questionTypeName,proto3" json:"question_type_name,omitempty"`
}

func (x *FormItems) Reset() {
	*x = FormItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormItems) ProtoMessage() {}

func (x *FormItems) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormItems.ProtoReflect.Descriptor instead.
func (*FormItems) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{8}
}

func (x *FormItems) GetContent() *FormItemContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FormItems) GetQuestionTypeName() string {
	if x != nil {
		return x.QuestionTypeName
	}
	return ""
}

type FormItemContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentTitle string                    `protobuf:"bytes,1,opt,name=content_title,json=contentTitle,proto3" json:"content_title,omitempty"`
	ContentType  string                    `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentUuid  string                    `protobuf:"bytes,3,opt,name=content_uuid,json=contentUuid,proto3" json:"content_uuid,omitempty"`
	Options      []*FormItemContentOptions `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Extend       *FormItemContentExtend    `protobuf:"bytes,5,opt,name=extend,proto3" json:"extend,omitempty"`
	UserAnswer   *UserAnswer               `protobuf:"bytes,6,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
}

func (x *FormItemContent) Reset() {
	*x = FormItemContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormItemContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormItemContent) ProtoMessage() {}

func (x *FormItemContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormItemContent.ProtoReflect.Descriptor instead.
func (*FormItemContent) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{9}
}

func (x *FormItemContent) GetContentTitle() string {
	if x != nil {
		return x.ContentTitle
	}
	return ""
}

func (x *FormItemContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FormItemContent) GetContentUuid() string {
	if x != nil {
		return x.ContentUuid
	}
	return ""
}

func (x *FormItemContent) GetOptions() []*FormItemContentOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FormItemContent) GetExtend() *FormItemContentExtend {
	if x != nil {
		return x.Extend
	}
	return nil
}

func (x *FormItemContent) GetUserAnswer() *UserAnswer {
	if x != nil {
		return x.UserAnswer
	}
	return nil
}

type FormItemContentOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionType    string                         `protobuf:"bytes,1,opt,name=option_type,json=optionType,proto3" json:"option_type,omitempty"`
	OptionValue   string                         `protobuf:"bytes,2,opt,name=option_value,json=optionValue,proto3" json:"option_value,omitempty"`
	OptionContent *FormItemContentOptionsContent `protobuf:"bytes,3,opt,name=option_content,json=optionContent,proto3" json:"option_content,omitempty"`
}

func (x *FormItemContentOptions) Reset() {
	*x = FormItemContentOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormItemContentOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormItemContentOptions) ProtoMessage() {}

func (x *FormItemContentOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormItemContentOptions.ProtoReflect.Descriptor instead.
func (*FormItemContentOptions) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{10}
}

func (x *FormItemContentOptions) GetOptionType() string {
	if x != nil {
		return x.OptionType
	}
	return ""
}

func (x *FormItemContentOptions) GetOptionValue() string {
	if x != nil {
		return x.OptionValue
	}
	return ""
}

func (x *FormItemContentOptions) GetOptionContent() *FormItemContentOptionsContent {
	if x != nil {
		return x.OptionContent
	}
	return nil
}

type UserAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Other    string   `protobuf:"bytes,1,opt,name=other,proto3" json:"other,omitempty"`
	Select   string   `protobuf:"bytes,2,opt,name=select,proto3" json:"select,omitempty"`
	ArrValue []string `protobuf:"bytes,3,rep,name=arr_value,json=arrValue,proto3" json:"arr_value,omitempty"`
}

func (x *UserAnswer) Reset() {
	*x = UserAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnswer) ProtoMessage() {}

func (x *UserAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnswer.ProtoReflect.Descriptor instead.
func (*UserAnswer) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{11}
}

func (x *UserAnswer) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

func (x *UserAnswer) GetSelect() string {
	if x != nil {
		return x.Select
	}
	return ""
}

func (x *UserAnswer) GetArrValue() []string {
	if x != nil {
		return x.ArrValue
	}
	return nil
}

type FormItemContentExtend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Require bool `protobuf:"varint,1,opt,name=require,proto3" json:"require,omitempty"`
}

func (x *FormItemContentExtend) Reset() {
	*x = FormItemContentExtend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormItemContentExtend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormItemContentExtend) ProtoMessage() {}

func (x *FormItemContentExtend) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormItemContentExtend.ProtoReflect.Descriptor instead.
func (*FormItemContentExtend) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{12}
}

func (x *FormItemContentExtend) GetRequire() bool {
	if x != nil {
		return x.Require
	}
	return false
}

type FormItemContentOptionsContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Explain string `protobuf:"bytes,2,opt,name=explain,proto3" json:"explain,omitempty"`
	Img     string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *FormItemContentOptionsContent) Reset() {
	*x = FormItemContentOptionsContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormItemContentOptionsContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormItemContentOptionsContent) ProtoMessage() {}

func (x *FormItemContentOptionsContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormItemContentOptionsContent.ProtoReflect.Descriptor instead.
func (*FormItemContentOptionsContent) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{13}
}

func (x *FormItemContentOptionsContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FormItemContentOptionsContent) GetExplain() string {
	if x != nil {
		return x.Explain
	}
	return ""
}

func (x *FormItemContentOptionsContent) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

type FormListResp_FormList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FormTitle string `protobuf:"bytes,2,opt,name=form_title,json=formTitle,proto3" json:"form_title,omitempty"`
	SubTitle  string `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
}

func (x *FormListResp_FormList) Reset() {
	*x = FormListResp_FormList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_box_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormListResp_FormList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormListResp_FormList) ProtoMessage() {}

func (x *FormListResp_FormList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_box_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormListResp_FormList.ProtoReflect.Descriptor instead.
func (*FormListResp_FormList) Descriptor() ([]byte, []int) {
	return file_api_v1_box_proto_rawDescGZIP(), []int{6, 0}
}

func (x *FormListResp_FormList) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FormListResp_FormList) GetFormTitle() string {
	if x != nil {
		return x.FormTitle
	}
	return ""
}

func (x *FormListResp_FormList) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

var File_api_v1_box_proto protoreflect.FileDescriptor

var file_api_v1_box_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x18, 0x46, 0x6f, 0x72, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x20, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x22, 0x3a, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2b, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x3a, 0x0a,
	0x0b, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x04,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x0d, 0x0a, 0x0b, 0x46, 0x6f, 0x72,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0xa2, 0x01, 0x0a, 0x0c, 0x46, 0x6f, 0x72,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x1a, 0x5a, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x93, 0x01,
	0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x72,
	0x6d, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x71, 0x0a, 0x09, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb1, 0x02, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x6d, 0x49,
	0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x12, 0x38, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x16, 0x46,
	0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x57, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x72, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x74, 0x65,
	0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x22, 0x5f, 0x0a, 0x1d, 0x46, 0x6f, 0x72, 0x6d,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x32, 0xb4, 0x04, 0x0a, 0x03, 0x42, 0x6f,
	0x78, 0x12, 0x45, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x13, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x7a, 0x0a, 0x14, 0x46, 0x6f, 0x72, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x25, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x72,
	0x6d, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x55, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x6d, 0x47, 0x65, 0x74, 0x12,
	0x17, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f,
	0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x56, 0x0a, 0x08, 0x46,
	0x6f, 0x72, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x61, 0x76, 0x65,
	0x3a, 0x01, 0x2a, 0x12, 0x63, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x6d, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x53, 0x61, 0x76, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22,
	0x14, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x5f, 0x73, 0x61, 0x76, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x56, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_box_proto_rawDescOnce sync.Once
	file_api_v1_box_proto_rawDescData = file_api_v1_box_proto_rawDesc
)

func file_api_v1_box_proto_rawDescGZIP() []byte {
	file_api_v1_box_proto_rawDescOnce.Do(func() {
		file_api_v1_box_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_box_proto_rawDescData)
	})
	return file_api_v1_box_proto_rawDescData
}

var file_api_v1_box_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_v1_box_proto_goTypes = []interface{}{
	(*Result)(nil),                        // 0: golayout.v1.Result
	(*FormListQuestionTypeResp)(nil),      // 1: golayout.v1.FormListQuestionTypeResp
	(*FormGetReq)(nil),                    // 2: golayout.v1.FormGetReq
	(*FormGetResp)(nil),                   // 3: golayout.v1.FormGetResp
	(*FormSaveReq)(nil),                   // 4: golayout.v1.FormSaveReq
	(*FormListReq)(nil),                   // 5: golayout.v1.FormListReq
	(*FormListResp)(nil),                  // 6: golayout.v1.FormListResp
	(*FormStruct)(nil),                    // 7: golayout.v1.FormStruct
	(*FormItems)(nil),                     // 8: golayout.v1.FormItems
	(*FormItemContent)(nil),               // 9: golayout.v1.FormItemContent
	(*FormItemContentOptions)(nil),        // 10: golayout.v1.FormItemContentOptions
	(*UserAnswer)(nil),                    // 11: golayout.v1.UserAnswer
	(*FormItemContentExtend)(nil),         // 12: golayout.v1.FormItemContentExtend
	(*FormItemContentOptionsContent)(nil), // 13: golayout.v1.FormItemContentOptionsContent
	(*FormListResp_FormList)(nil),         // 14: golayout.v1.FormListResp.FormList
	(*anypb.Any)(nil),                     // 15: google.protobuf.Any
	(*emptypb.Empty)(nil),                 // 16: google.protobuf.Empty
}
var file_api_v1_box_proto_depIdxs = []int32{
	15, // 0: golayout.v1.Result.data:type_name -> google.protobuf.Any
	8,  // 1: golayout.v1.FormListQuestionTypeResp.list:type_name -> golayout.v1.FormItems
	7,  // 2: golayout.v1.FormGetResp.form:type_name -> golayout.v1.FormStruct
	7,  // 3: golayout.v1.FormSaveReq.form:type_name -> golayout.v1.FormStruct
	14, // 4: golayout.v1.FormListResp.list:type_name -> golayout.v1.FormListResp.FormList
	8,  // 5: golayout.v1.FormStruct.items:type_name -> golayout.v1.FormItems
	9,  // 6: golayout.v1.FormItems.content:type_name -> golayout.v1.FormItemContent
	10, // 7: golayout.v1.FormItemContent.options:type_name -> golayout.v1.FormItemContentOptions
	12, // 8: golayout.v1.FormItemContent.extend:type_name -> golayout.v1.FormItemContentExtend
	11, // 9: golayout.v1.FormItemContent.user_answer:type_name -> golayout.v1.UserAnswer
	13, // 10: golayout.v1.FormItemContentOptions.option_content:type_name -> golayout.v1.FormItemContentOptionsContent
	16, // 11: golayout.v1.Box.Ping:input_type -> google.protobuf.Empty
	16, // 12: golayout.v1.Box.FormListQuestionType:input_type -> google.protobuf.Empty
	2,  // 13: golayout.v1.Box.FormGet:input_type -> golayout.v1.FormGetReq
	4,  // 14: golayout.v1.Box.FormSave:input_type -> golayout.v1.FormSaveReq
	4,  // 15: golayout.v1.Box.FormAnswerSave:input_type -> golayout.v1.FormSaveReq
	5,  // 16: golayout.v1.Box.FormList:input_type -> golayout.v1.FormListReq
	0,  // 17: golayout.v1.Box.Ping:output_type -> golayout.v1.Result
	1,  // 18: golayout.v1.Box.FormListQuestionType:output_type -> golayout.v1.FormListQuestionTypeResp
	3,  // 19: golayout.v1.Box.FormGet:output_type -> golayout.v1.FormGetResp
	16, // 20: golayout.v1.Box.FormSave:output_type -> google.protobuf.Empty
	16, // 21: golayout.v1.Box.FormAnswerSave:output_type -> google.protobuf.Empty
	6,  // 22: golayout.v1.Box.FormList:output_type -> golayout.v1.FormListResp
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_v1_box_proto_init() }
func file_api_v1_box_proto_init() {
	if File_api_v1_box_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_box_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormListQuestionTypeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormSaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormItemContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormItemContentOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormItemContentExtend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormItemContentOptionsContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_box_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormListResp_FormList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_box_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_box_proto_goTypes,
		DependencyIndexes: file_api_v1_box_proto_depIdxs,
		MessageInfos:      file_api_v1_box_proto_msgTypes,
	}.Build()
	File_api_v1_box_proto = out.File
	file_api_v1_box_proto_rawDesc = nil
	file_api_v1_box_proto_goTypes = nil
	file_api_v1_box_proto_depIdxs = nil
}
