// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/comeonjy/go-kit/pkg/xlog"
	"github.com/comeonjy/box/configs"
	"github.com/comeonjy/box/internal/data"
	"github.com/comeonjy/box/internal/server"
	"github.com/comeonjy/box/internal/service"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *xlog.Logger) *App {
	configsInterface := configs.NewConfig(ctx)
	dataData := data.NewData(configsInterface)
	workRepo := data.NewWorkRepo(dataData)
	schedulerService := service.NewSchedulerService(configsInterface, logger, workRepo)
	grpcServer := server.NewGrpcServer(schedulerService, configsInterface, logger)
	httpServer := server.NewHttpServer(ctx, configsInterface, logger)
	app := newApp(ctx, grpcServer, httpServer, configsInterface)
	return app
}
