// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: configs/config.proto

package configs

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode"`
	MysqlConf            string   `protobuf:"bytes,2,opt,name=mysql_conf,json=mysqlConf,proto3" json:"mysql_conf"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_20df995425c1619e, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *Config) GetMysqlConf() string {
	if m != nil {
		return m.MysqlConf
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "configs.Config")
}

func init() { proto.RegisterFile("configs/config.proto", fileDescriptor_20df995425c1619e) }

var fileDescriptor_20df995425c1619e = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0x2f, 0xd6, 0x87, 0xd0, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0x51,
	0x29, 0xf1, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0x54, 0x7d, 0x18, 0x03, 0xa2, 0x42, 0x8a,
	0x3f, 0x3d, 0x3f, 0x3d, 0x5f, 0x1f, 0x44, 0x40, 0x04, 0x94, 0x32, 0xb9, 0xd8, 0x9c, 0xc1, 0x9a,
	0x84, 0x0c, 0xb8, 0x58, 0x72, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x9d, 0x64,
	0x7e, 0x39, 0x09, 0x16, 0xf1, 0x07, 0xb1, 0xa6, 0xa4, 0x26, 0x95, 0xa6, 0x07, 0xb1, 0xe5, 0xe5,
	0x17, 0xe5, 0x26, 0xe6, 0xbc, 0xba, 0x27, 0x0f, 0x56, 0x13, 0x04, 0x26, 0x85, 0x74, 0xb9, 0xb8,
	0x72, 0x2b, 0x8b, 0x0b, 0x73, 0xe2, 0x41, 0xd6, 0x4a, 0x30, 0x81, 0xf5, 0xf1, 0xbd, 0xba, 0x27,
	0x8f, 0x24, 0x1a, 0xc4, 0x09, 0x66, 0x83, 0xac, 0x70, 0xe2, 0x8e, 0xe2, 0xd4, 0xb3, 0x86, 0xba,
	0x30, 0x89, 0x0d, 0x6c, 0xbd, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x03, 0x01, 0xc5, 0xc9,
	0x00, 0x00, 0x00,
}
